version: "3.2"
services:
  frontend:
    image: "${IMAGE_NAME}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker        
    networks:
      - zwp-proxy-network
networks:
  zwp-proxy-network:
    external: true