import { PageObjects } from '../../support/pageObjects';
import { CONSTANT } from '../../fixtures/constants';

class PlanAddOns {

    clickOnPlus() {
        cy.get('[data-cy="plusIcon"]').click({force: true});
        return this;
    };

    clickOnMinus() {
        cy.get('[data-cy="minusIcon"]').click({force: true});
        return this;
    };

    clickOnSelectAddOns() {
        cy.get('[data-cy="selectAddOn"]').click({force: true});
        return this;
    };
    clickToSelectAnMdn(){
        cy.get('.menu > #phonePlan').click({force: true});
        cy.contains(' (512) 203-4783 ').click({force: true});
    };
    clickOnProceedCheckout() {
        cy.get('[data-cy="proceedCheckout"]').click({force: true});
        cy.wait(CONSTANT.TIME.SPEED_TIME.LEVEL2);
        return this;
    };
    orderDataAddOnsDeleteIt(){
        PageObjects.AccountSummary.clickOnPlanAddOns();
        PageObjects.TitleExpectations.goToPlanAddOnsPage();
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '1');
        cy.get('.total').should('have.text', '$10');
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '2');
        cy.get('.total').should('have.text', '$20');
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '3');
        cy.get('.total').should('have.text', '$30');
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '4');
        cy.get('.total').should('have.text', '$40');
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '5');
        cy.get('.total').should('have.text', '$50');
        cy.get('[data-cy="plusIcon"]').should('be.disabled');
        this.clickOnMinus();
        cy.get('.quantityNum').should('have.value', '4');
        cy.get('.total').should('have.text', '$40');
        this.clickOnMinus();
        cy.get('.quantityNum').should('have.value', '3');
        cy.get('.total').should('have.text', '$30');
        this.clickOnMinus();
        cy.get('.quantityNum').should('have.value', '2');
        cy.get('.total').should('have.text', '$20');
        this.clickOnMinus();
        cy.get('.quantityNum').should('have.value', '1');
        cy.get('.total').should('have.text', '$10');
        this.clickOnMinus();
        cy.get('.quantityNum').should('have.value', '0');
        cy.get('[data-cy="minusIcon"]').should('be.disabled');
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '1');
        cy.get('.total').should('have.text', '$10');
        this.clickOnProceedCheckout();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('.head-title').should('have.text', 'Review your cart');
        cy.get('[data-cy="addOnsPlan"]').should('have.text','Plan Data Add-On');
        cy.get('[data-cy="dataAddOns"]').should('have.text','(Data Add-On)');
        cy.get('[data-cy="subtotal"]').should('have.text','Item(s) price: $10.00');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        cy.get('[data-cy="creditCardPayment"]').click();
        PageObjects.Payment.selectFirstPaymentMethod();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('.subtotal').should('have.text', ' Total: $11.52 '); 
        cy.get('[data-cy="addOnsPlan"]').should('have.text','Plan Data Add-On');
        cy.get('[data-cy="dataAddOns"]').should('have.text','(Data Add-On)');
        PageObjects.PlaceOrder.deletePlan();
        PageObjects.PlaceOrder.clickOnYesFromThePopUp();
    };
    orderInternationalCalling(){
        PageObjects.AccountSummary.clickOnPlanAddOns();
        PageObjects.TitleExpectations.goToPlanAddOnsPage();
        cy.get('[data-cy="internationalCalling"]').click();
        cy.get('[data-cy="internationalCallingHeader"]').should('have.text','Stay in touch with family & friends around the world!');
        this.clickOnProceedCheckout();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('[data-cy="internationalPayGoPlan"]').should('have.text','Pay Go International');
        cy.get('[data-cy="talkTextAddOns"]').should('have.text','(Talk & text add-on)');
        cy.get('[data-cy="subtotal"]').should('have.text','Item(s) price: $5.00');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        cy.get('[data-cy="creditCardPayment"]').click();
        PageObjects.Payment.selectFirstPaymentMethod();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('.subtotal').should('have.text', ' Total: $5.70 '); 
        cy.get('[data-cy="internationalPayGoPlan"]').should('have.text','Pay Go International');
        cy.get('[data-cy="talkTextAddOns"]').should('have.text','(Talk & text add-on)');
        PageObjects.PlaceOrder.deletePlan();
        PageObjects.PlaceOrder.clickOnYesFromThePopUp();
    };
    purchaseDataAddOnsInternationalCallingDeleteIt(){
        PageObjects.AccountSummary.clickOnPlanAddOns();
        PageObjects.TitleExpectations.goToPlanAddOnsPage();
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '1');
        cy.get('.total').should('have.text', '$10');
        this.clickOnSelectAddOns();
        cy.get('[data-cy="cancel-btn"]').click();
        cy.get('[data-cy="internationalCalling"]').click();
        cy.get('[data-cy="internationalCallingHeader"]').should('have.text','Stay in touch with family & friends around the world!');
        this.clickOnProceedCheckout();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('.head-title').should('have.text', 'Review your cart');
        cy.get('[data-cy="addOnsPlan"]').should('have.text','Plan Data Add-On');
        cy.get('[data-cy="dataAddOns"]').should('have.text','(Data Add-On)');
        cy.get('[data-cy="internationalPayGoPlan"]').should('have.text','Pay Go International');
        cy.get('[data-cy="talkTextAddOns"]').should('have.text','(Talk & text add-on)');
        cy.get('[data-cy="subtotal"]').should('have.text','Item(s) price: $15.00');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        cy.get('[data-cy="creditCardPayment"]').click();
        PageObjects.Payment.selectFirstPaymentMethod();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('.subtotal').should('have.text', ' Total: $17.27 '); 
        cy.get('[data-cy="addOnsPlan"]').should('have.text','Plan Data Add-On');
        cy.get('[data-cy="dataAddOns"]').should('have.text','(Data Add-On)');
        cy.get('[data-cy="internationalPayGoPlan"]').should('have.text','Pay Go International');
        cy.get('[data-cy="talkTextAddOns"]').should('have.text','(Talk & text add-on)');
        cy.get(':nth-child(1) > .details > .actions > [data-cy="deletePlan"]').click();
        PageObjects.PlaceOrder.clickOnYesFromThePopUp();
        cy.wait(CONSTANT.TIME.SPEED_TIME.LEVEL1);
        PageObjects.PlaceOrder.deletePlan();
        PageObjects.PlaceOrder.clickOnYesFromThePopUp();
    };
    purchaseDataAddOns(){
        PageObjects.AccountSummary.clickOnPlanAddOns();
        PageObjects.TitleExpectations.goToPlanAddOnsPage();
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '1');
        cy.get('.total').should('have.text', '$10');
        this.clickOnProceedCheckout();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('.head-title').should('have.text', 'Review your cart');
        cy.get('[data-cy="addOnsPlan"]').should('have.text','Plan Data Add-On');
        cy.get('[data-cy="dataAddOns"]').should('have.text','(Data Add-On)');
        cy.get('[data-cy="subtotal"]').should('have.text','Item(s) price: $10.00');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        cy.get('[data-cy="creditCardPayment"]').click();
        PageObjects.Payment.selectFirstPaymentMethod();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('.subtotal').should('have.text', ' Total: $11.40 '); 
        cy.get('[data-cy="addOnsPlan"]').should('have.text','Plan Data Add-On');
        cy.get('[data-cy="dataAddOns"]').should('have.text','(Data Add-On)');
        PageObjects.PlaceOrder.clickOnSubmitBtn();
        PageObjects.TitleExpectations.goToPurchaseSuccessfulPage();
        cy.get('[data-cy="purchasedAddOns"]').should('have.text','You can view your plan and add-on details through your Account Summary page. ');
        PageObjects.AccountSummary.clickOnGoAccountToSummaryBtn();
        PageObjects.TitleExpectations.goToAccountSummaryPage();
    };
    assertUserHasDataAddOnsInternationalCalling(){
        cy.get('[data-cy="addOns"]').should('not.exist');
        cy.get('[data-cy="addOnsInfo"]').should('have.text','1 * 1GB 4G LTE');
        cy.get('[data-cy="payGoInfo"]').should('have.text','3 * Individual Country Calling');
        cy.get('[data-cy="orderAddOns"]').should('exist');
        PageObjects.TitleExpectations.goToAccountSummaryPage();
    };
    assertUserHasOneDataAddOns(){
        cy.get('[data-cy="addOnsInfo"]').should('have.text','1 * 1GB 4G LTE');
        cy.get('[data-cy="addOnsPrice"]').should('have.text','$10.00');
        PageObjects.AccountSummary.clickOnPlanAddOns();
        PageObjects.TitleExpectations.goToPlanAddOnsPage();
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '1');
        cy.get('.total').should('have.text', '$10');
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '2');
        cy.get('.total').should('have.text', '$20');
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '3');
        cy.get('.total').should('have.text', '$30');
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '4');
        cy.get('.total').should('have.text', '$40');
        cy.get('[data-cy="plusIcon"]').should('be.disabled');
        this.clickOnMinus();
        cy.get('.quantityNum').should('have.value', '3');
        cy.get('.total').should('have.text', '$30');
        this.clickOnMinus();
        cy.get('.quantityNum').should('have.value', '2');
        cy.get('.total').should('have.text', '$20');
        this.clickOnMinus();
        cy.get('.quantityNum').should('have.value', '1');
        cy.get('.total').should('have.text', '$10');
        this.clickOnMinus();
        cy.get('.quantityNum').should('have.value', '0');
        cy.get('[data-cy="minusIcon"]').should('be.disabled');
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '1');
        cy.get('.total').should('have.text', '$10');
        this.clickOnProceedCheckout();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('.head-title').should('have.text', 'Review your cart');
        cy.get('[data-cy="addOnsPlan"]').should('have.text','Plan Data Add-On');
        cy.get('[data-cy="dataAddOns"]').should('have.text','(Data Add-On)');
        cy.get('[data-cy="subtotal"]').should('have.text','Item(s) price: $10.00');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        cy.get('[data-cy="creditCardPayment"]').click();
        PageObjects.Payment.selectFirstPaymentMethod();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('.subtotal').should('have.text', ' Total: $11.38 '); 
        cy.get('[data-cy="addOnsPlan"]').should('have.text','Plan Data Add-On');
        cy.get('[data-cy="dataAddOns"]').should('have.text','(Data Add-On)');
        PageObjects.PlaceOrder.deletePlan();
        PageObjects.PlaceOrder.clickOnYesFromThePopUp();
    };
    assertUserHasMultipleDataAddOns(){
        cy.get('[data-cy="addOnsInfo"]').should('have.text','3 * 1GB 4G LTE');
        cy.get('[data-cy="addOnsPrice"]').should('have.text','$10.00');
        PageObjects.AccountSummary.clickOnPlanAddOns();
        PageObjects.TitleExpectations.goToPlanAddOnsPage();
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '1');
        cy.get('.total').should('have.text', '$10');
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '2');
        cy.get('.total').should('have.text', '$20');
        cy.get('[data-cy="plusIcon"]').should('be.disabled');
        this.clickOnMinus();
        cy.get('.quantityNum').should('have.value', '1');
        cy.get('.total').should('have.text', '$10');
        this.clickOnMinus();
        cy.get('.quantityNum').should('have.value', '0');
        cy.get('[data-cy="minusIcon"]').should('be.disabled');
        this.clickOnPlus();
        cy.get('.quantityNum').should('have.value', '1');
        cy.get('.total').should('have.text', '$10');
        this.clickOnProceedCheckout();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('.head-title').should('have.text', 'Review your cart');
        cy.get('[data-cy="addOnsPlan"]').should('have.text','Plan Data Add-On');
        cy.get('[data-cy="dataAddOns"]').should('have.text','(Data Add-On)');
        cy.get('[data-cy="subtotal"]').should('have.text','Item(s) price: $10.00');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        cy.get('[data-cy="creditCardPayment"]').click();
        PageObjects.Payment.selectFirstPaymentMethod();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('.subtotal').should('have.text', ' Total: $11.56 '); 
        cy.get('[data-cy="addOnsPlan"]').should('have.text','Plan Data Add-On');
        cy.get('[data-cy="dataAddOns"]').should('have.text','(Data Add-On)');
        PageObjects.PlaceOrder.deletePlan();
        PageObjects.PlaceOrder.clickOnYesFromThePopUp();
    };
};
export default new PlanAddOns();