import { CONSTANT } from '../../fixtures/constants/index';
import { PageObjects } from '../../support/pageObjects';

class PurchasedPlans {

    clickOnEditShippingAddressIcon() {
        cy.get('[data-cy="editIcon"]').click();
        return this;
    };

    editShippingInfo(name, address, suite, city, state,postal) {
        cy.get('[data-cy="addressName"]').clear();
        cy.get('[data-cy="addressName"]').type(name);
        cy.get('[data-cy="addressLookup"]').clear();
        cy.get('[data-cy="addressLookup"]').type(address);
        cy.get('[data-cy="suiteNo"]').clear();
        cy.get('[data-cy="suiteNo"]').type(suite);
        cy.get('[data-cy="billingCity"]').clear();
        cy.get('[data-cy="billingCity"]').type(city);
        cy.get('[data-cy="billingState"]').clear();
        cy.get('[data-cy="billingState"]').type(state);
        cy.get('[data-cy="billingPostal"]').clear();
        cy.get('[data-cy="billingPostal"]').type(postal);
        cy.get('[data-cy="addressLookup"]').click();
        return this;
    };

    clickOnSaveBtn() {
        cy.get('[data-cy="save"]').click();
        return this;
    };
    clickOnKeepCurrentAddress() {
        cy.get('.display-block > [data-cy="action-button"]').click();
        return this;
    };
    clickOnUseVerifiedAddress() {
        cy.get(':nth-child(3) > [data-cy="action-button"]').click();
        cy.wait(CONSTANT.TIME.SPEED_TIME.LEVEL2);
        return this;
    };
    clickOnActivatePlanButton() {
        cy.get(':nth-child(1) > .button').click();
        return this;
    };
    purchasePlanWithStorePickupExistingCustomer(){
        PageObjects.HomePage.clickOnShopMenu();
        PageObjects.TitleExpectations.goToPlansGMPage();
        PageObjects.Plans.clickOnCartIcon();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressIsRequired();
        PageObjects.Coverage.addressRefNotSelectedFromList();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressNotSelectedFromList();
        cy.get('[data-cy="addressRef"]').clear();
        PageObjects.Coverage.enterAddressRefBothCoverages();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        cy.get('.banner-content > .title').should('have.text', ' Great News!');
        PageObjects.Coverage.clickOnNextStepBtn();
        PageObjects.Compatibility.clickOnCheckYourDevice();
        PageObjects.Compatibility.assertIMEInumberRequired();
        PageObjects.Compatibility.enterIMEInumber(CONSTANT.COMPATIBILITY.NEWMEID.INVALID_MEID);
        PageObjects.Compatibility.assertIMEInumberInvalid();
        PageObjects.Compatibility.clickOnSkipForNowLink();
        PageObjects.Compatibility.clickOnYesFromThePopUp();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('.head-title').should('have.text', 'Review your cart');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToShippingPage();
        PageObjects.ShippingPage.clickOnStorePickup();
        PageObjects.ShippingPage.barCodeValNotChecked();
        cy.get('#barCodeVal').click();
        PageObjects.ShippingPage.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.Payment.paymentRequired();
        PageObjects.Payment.selectFirstPaymentMethod();
        PageObjects.Payment.clickOnBackBtnPaymentAssertPickupOptionShipping();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('[data-cy="deliveryMethod"]').should('have.text', 'Store Pickup');
        PageObjects.PlaceOrder.clickOnSubmitBtn();
        PageObjects.TitleExpectations.goToPurchaseSuccessfulPage();
        cy.get('[data-cy="storePickupSuccessful"]').should('have.text','Your Store pickup barcode is available in your purchased plans page.')
        cy.get('[data-cy="purchasedPlansBtn"]').click();
        PageObjects.TitleExpectations.goToPurchasedPlansPage();
    };
    assertPurchasedPlanWithStorePickupExistingCustomer(){
        PageObjects.AccountSummary.clickOnPurchasedPlans();
        PageObjects.TitleExpectations.goToPurchasedPlansPage();
        cy.get('[data-cy="pendingPlans"]').should('have.text','6GB 4G LTE Plan');
        cy.get('[data-cy="planTitle"]').should('have.text',' Unlimited Talk & text with 6GB Data');
        cy.get('[data-cy="simType"]').should('have.text','SIM Card');
        cy.get('[data-cy="pickupBarCode"]').should('have.text','In-store Pickup Barcode');
        cy.get('[data-cy="barcode"]').should('be.visible');
        cy.get('[data-cy="deliveryOption"]').should('have.text','Store Pickup');
    };
    assertPurchased6GBPlanWithHomeDelivery(){
        PageObjects.AccountSummary.clickOnPurchasedPlans();
        PageObjects.TitleExpectations.goToPurchasedPlansPage();
        cy.get('[data-cy="pendingPlans"]').should('have.text','6GB 4G LTE Plan');
        cy.get('[data-cy="planTitle"]').should('have.text',' Unlimited Talk & text with 6GB Data');
        cy.get('[data-cy="simType"]').should('have.text','SIM Card');
        cy.get('[data-cy="deliveryOption"]').should('have.text','Home Delivery');
    };
    assertPurchased2GBPlanWithHomeDelivery(){
        PageObjects.AccountSummary.clickOnPurchasedPlans();
        PageObjects.TitleExpectations.goToPurchasedPlansPage();
        cy.get('[data-cy="pendingPlans"]').should('have.text','2GB 4G LTE Plan');
        cy.get('[data-cy="planTitle"]').should('have.text',' Unlimited Talk & text with 2GB Data');
        cy.get('[data-cy="simType"]').should('have.text','SIM Card');
        cy.get('[data-cy="deliveryOption"]').should('have.text','Home Delivery');
    };
    assertPurchased15GBPlanWithHomeDelivery(){
        PageObjects.AccountSummary.clickOnPurchasedPlans();
        PageObjects.TitleExpectations.goToPurchasedPlansPage();
        cy.get('[data-cy="pendingPlans"]').should('have.text','15GB 4G LTE Plan');
        cy.get('[data-cy="planTitle"]').should('have.text',' Unlimited Talk & text with 15GB Data');
        cy.get('[data-cy="simType"]').should('have.text','SIM Card');
        cy.get('[data-cy="deliveryOption"]').should('have.text','Home Delivery');
    };
    purchase2GBPlanWithHomeDeliveryExistingCustomerPlansPage(){
        PageObjects.HomePage.clickOnShopMenu();
        PageObjects.HomePage.clickOnPlans();
        PageObjects.TitleExpectations.goToPlansGMPage();
        PageObjects.Plans.clickOnPlan_2_GB_Plans_Page();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressIsRequired();
        PageObjects.Coverage.addressRefNotSelectedFromList();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressNotSelectedFromList();
        cy.get('[data-cy="addressRef"]').clear();
        PageObjects.Coverage.enterAddressRefBothCoverages();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        cy.get('.banner-content > .title').should('have.text', ' Great News!');
        PageObjects.Coverage.clickOnNextStepBtn();
        PageObjects.Compatibility.clickOnCheckYourDevice();
        PageObjects.Compatibility.assertIMEInumberRequired();
        PageObjects.Compatibility.enterIMEInumber(CONSTANT.COMPATIBILITY.NEWMEID.INVALID_MEID);
        PageObjects.Compatibility.assertIMEInumberInvalid();
        PageObjects.Compatibility.clickOnSkipForNowLink();
        PageObjects.Compatibility.clickOnYesFromThePopUp();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('.head-title').should('have.text', 'Review your cart');
        cy.get('[data-cy="basePlan"]').should('have.text','2GB 4G LTE Plan');
        cy.get('[data-cy="subtotal"]').should('have.text','Item(s) price: $10.00');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToShippingPage();
        PageObjects.ShippingPage.clickOnHomeDelivery();
        PageObjects.ShippingPage.selectShippingInfo();
        cy.get('select').eq(0).select('USPS', { force: true }).should('have.value', 'usps');
        cy.get('select').eq(1).select('First Class Mail Shipping 3-7 Business days', { force: true }).should('have.value', 'usps_first_class_mail/letter');
        PageObjects.ShippingPage.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.Payment.paymentRequired();
        PageObjects.Payment.selectFirstPaymentMethod();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('.subtotal').should('have.text', ' Total: $13.02 '); 
        cy.get('[data-cy="basePlan"]').should('have.text', '2GB 4G LTE Plan');
        cy.get('[data-cy="deliveryMethod"]').should('have.text', 'Home Delivery');
        PageObjects.PlaceOrder.clickOnSubmitBtn();
        PageObjects.TitleExpectations.goToPurchaseSuccessfulPage();
        cy.get('[data-cy="homeDeliverySuccessfulNewSIM"]').should('have.text','Lookout for your new SIM Card in the mail!');
        cy.get('[data-cy="activateNewSIM"]').should('have.text',' Once your SIM card arrives in a couple of days, we will help you get your SIM card activated with a brand new phone number, or transfer your active number (port in) from another provider. You can view your plan details and activate it through your Purchased Plans page. ');
        cy.get('[data-cy="purchasedPlansBtn"]').click();
        PageObjects.TitleExpectations.goToPurchasedPlansPage();
    };
    purchase6GBPlanWithHomeDeliveryExistingCustomerPlansPage(){
        PageObjects.HomePage.clickOnShopMenu();
        PageObjects.HomePage.clickOnPlans();
        PageObjects.TitleExpectations.goToPlansGMPage();
        PageObjects.Plans.clickOn6GB_From_Plans_Page();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressIsRequired();
        PageObjects.Coverage.addressRefNotSelectedFromList();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressNotSelectedFromList();
        cy.get('[data-cy="addressRef"]').clear();
        PageObjects.Coverage.enterAddressRefBothCoverages();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        cy.get('.banner-content > .title').should('have.text', ' Great News!');
        PageObjects.Coverage.clickOnNextStepBtn();
        PageObjects.Compatibility.clickOnCheckYourDevice();
        PageObjects.Compatibility.assertIMEInumberRequired();
        PageObjects.Compatibility.enterIMEInumber(CONSTANT.COMPATIBILITY.NEWMEID.INVALID_MEID);
        PageObjects.Compatibility.assertIMEInumberInvalid();
        PageObjects.Compatibility.clickOnSkipForNowLink();
        PageObjects.Compatibility.clickOnYesFromThePopUp();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('.head-title').should('have.text', 'Review your cart');
        cy.get('[data-cy="basePlan"]').should('have.text','6GB 4G LTE Plan');
        cy.get('[data-cy="subtotal"]').should('have.text','Item(s) price: $20.00');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToShippingPage();
        PageObjects.ShippingPage.clickOnHomeDelivery();
        PageObjects.ShippingPage.selectShippingInfo();
        cy.get('select').eq(0).select('USPS', { force: true }).should('have.value', 'usps');
        cy.get('select').eq(1).select('First Class Mail Shipping 3-7 Business days', { force: true }).should('have.value', 'usps_first_class_mail/letter');
        PageObjects.ShippingPage.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.Payment.paymentRequired();
        PageObjects.Payment.selectFirstPaymentMethod();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('.subtotal').should('have.text', ' Total: $24.54 ');
        cy.get('[data-cy="basePlan"]').should('have.text', '6GB 4G LTE Plan');
        cy.get('[data-cy="deliveryMethod"]').should('have.text', 'Home Delivery');
        PageObjects.PlaceOrder.clickOnSubmitBtn();
        PageObjects.TitleExpectations.goToPurchaseSuccessfulPage();
        cy.get('[data-cy="homeDeliverySuccessfulNewSIM"]').should('have.text','Lookout for your new SIM Card in the mail!');
        cy.get('[data-cy="activateNewSIM"]').should('have.text',' Once your SIM card arrives in a couple of days, we will help you get your SIM card activated with a brand new phone number, or transfer your active number (port in) from another provider. You can view your plan details and activate it through your Purchased Plans page. ');
        cy.get('[data-cy="purchasedPlansBtn"]').click();
        PageObjects.TitleExpectations.goToPurchasedPlansPage();
    };
    purchase15GBPlanWithHomeDeliveryExistingCustomerPlansPage(){
        PageObjects.HomePage.clickOnShopMenu();
        PageObjects.HomePage.clickOnPlans();
        PageObjects.TitleExpectations.goToPlansGMPage();
        PageObjects.Plans.clickOn15GB_From_Plans_Page();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressIsRequired();
        PageObjects.Coverage.addressRefNotSelectedFromList();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressNotSelectedFromList();
        cy.get('[data-cy="addressRef"]').clear();
        PageObjects.Coverage.enterAddressRefBothCoverages();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        cy.get('.banner-content > .title').should('have.text', ' Great News!');
        PageObjects.Coverage.clickOnNextStepBtn();
        PageObjects.Compatibility.clickOnCheckYourDevice();
        PageObjects.Compatibility.assertIMEInumberRequired();
        PageObjects.Compatibility.enterIMEInumber(CONSTANT.COMPATIBILITY.NEWMEID.INVALID_MEID);
        PageObjects.Compatibility.assertIMEInumberInvalid();
        PageObjects.Compatibility.clickOnSkipForNowLink();
        PageObjects.Compatibility.clickOnYesFromThePopUp();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('.head-title').should('have.text', 'Review your cart');
        cy.get('[data-cy="basePlan"]').should('have.text','15GB 4G LTE Plan');
        cy.get('[data-cy="subtotal"]').should('have.text','Item(s) price: $30.00');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToShippingPage();
        PageObjects.ShippingPage.clickOnHomeDelivery();
        PageObjects.ShippingPage.selectShippingInfo();
        cy.get('select').eq(0).select('USPS', { force: true }).should('have.value', 'usps');
        cy.get('select').eq(1).select('First Class Mail Shipping 3-7 Business days', { force: true }).should('have.value', 'usps_first_class_mail/letter');
        PageObjects.ShippingPage.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.Payment.paymentRequired();
        PageObjects.Payment.selectFirstPaymentMethod();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('.subtotal').should('have.text', ' Total: $35.09 ');
        cy.get('[data-cy="basePlan"]').should('have.text', '15GB 4G LTE Plan');
        cy.get('[data-cy="deliveryMethod"]').should('have.text', 'Home Delivery');
        PageObjects.PlaceOrder.clickOnSubmitBtn();
        PageObjects.TitleExpectations.goToPurchaseSuccessfulPage();
        cy.get('[data-cy="homeDeliverySuccessfulNewSIM"]').should('have.text','Lookout for your new SIM Card in the mail!');
        cy.get('[data-cy="activateNewSIM"]').should('have.text',' Once your SIM card arrives in a couple of days, we will help you get your SIM card activated with a brand new phone number, or transfer your active number (port in) from another provider. You can view your plan details and activate it through your Purchased Plans page. ');
        cy.get('[data-cy="purchasedPlansBtn"]').click();
        PageObjects.TitleExpectations.goToPurchasedPlansPage();
    };
    purchase2GBPlanWithHomeDeliveryNewUser(){
        PageObjects.TitleExpectations.goToWelcomeOnBoardPage();
        PageObjects.welcomeOnBoard.clickOnShopPlansBtn();
        PageObjects.TitleExpectations.goToPlansGMPage();
        PageObjects.Plans.clickOnPlan_2_GB_Plans_Page();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressIsRequired();
        PageObjects.Coverage.addressRefNotSelectedFromList();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressNotSelectedFromList();
        cy.get('[data-cy="addressRef"]').clear();
        PageObjects.Coverage.enterAddressRefBothCoverages();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        cy.get('.banner-content > .title').should('have.text', ' Great News!');
        PageObjects.Coverage.clickOnNextStepBtn();
        PageObjects.Compatibility.clickOnCheckYourDevice();
        PageObjects.Compatibility.assertIMEInumberRequired();
        PageObjects.Compatibility.enterIMEInumber(CONSTANT.COMPATIBILITY.NEWMEID.INVALID_MEID);
        PageObjects.Compatibility.assertIMEInumberInvalid();
        PageObjects.Compatibility.clickOnSkipForNowLink();
        PageObjects.Compatibility.clickOnYesFromThePopUp();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('.head-title').should('have.text', 'Review your cart');
        cy.get('[data-cy="basePlan"]').should('have.text','2GB 4G LTE Plan');
        cy.get('[data-cy="subtotal"]').should('have.text','Item(s) price: $10.00');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToShippingPage();
        PageObjects.ShippingPage.clickOnHomeDelivery();
        PageObjects.ShippingPage.addShippingInfo1(CONSTANT.SHIPPING.INVALID_SHIPPING_DATA.NAME,
            CONSTANT.SHIPPING.INVALID_SHIPPING_DATA.SHIPPING_ADDRESS,
            CONSTANT.SHIPPING.INVALID_SHIPPING_DATA.SUITE_NO);
        PageObjects.ShippingPage.addShippingInfo2(CONSTANT.SHIPPING.INVALID_SHIPPING_DATA.CITY,
            CONSTANT.SHIPPING.INVALID_SHIPPING_DATA.STATE,
            CONSTANT.SHIPPING.INVALID_SHIPPING_DATA.POSTAL);
        PageObjects.ShippingPage.assertInvalidShippingAddress();
        PageObjects.ShippingPage.addShippingInfo1(CONSTANT.SHIPPING.SHIPPING_DATA.NAME,
            CONSTANT.SHIPPING.SHIPPING_DATA.SHIPPING_ADDRESS,
            CONSTANT.SHIPPING.SHIPPING_DATA.SUITE_NO);
        PageObjects.ShippingPage.addShippingInfo2(CONSTANT.SHIPPING.VALID.CITY,
            CONSTANT.SHIPPING.SHIPPING_DATA.STATE,
            CONSTANT.SHIPPING.SHIPPING_DATA.POSTAL);
        PageObjects.ShippingPage.clickOnSaveBtn();
        PageObjects.ShippingPage.chooseVerifiedAddress();
        cy.get('select').eq(0).select('USPS', { force: true }).should('have.value', 'usps');
        cy.get('select').eq(1).select('First Class Mail Shipping 3-7 Business days', { force: true }).should('have.value', 'usps_first_class_mail/letter');
        PageObjects.ShippingPage.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        PageObjects.Payment.fillInPaymentInfo(CONSTANT.PAYMENT.CREDIT_CARD.INVALID_CARD.NAME_ON_CARD,
            CONSTANT.PAYMENT.CREDIT_CARD.INVALID_CARD_NUMBER.CARD_NUMBER,
            CONSTANT.PAYMENT.CREDIT_CARD.INVALID_CVV.CVV);
        PageObjects.Payment.addInvalidMonthAndYear();
        PageObjects.Payment.assertInvalidPament();
        PageObjects.Payment.fillInPaymentInfo(CONSTANT.PAYMENT.CREDIT_CARD.VALID.NAME_ON_CARD,
            CONSTANT.PAYMENT.CREDIT_CARD.VALID.PAN,
            CONSTANT.PAYMENT.CREDIT_CARD.VALID.CVV);
        PageObjects.Payment.addValidMonthAndYear();
        PageObjects.Payment.clickOnSaveBtn();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('.subtotal').should('have.text', ' Total: $13.06 '); 
        cy.get('[data-cy="basePlan"]').should('have.text', '2GB 4G LTE Plan');
        cy.get('[data-cy="deliveryMethod"]').should('have.text', 'Home Delivery');
        PageObjects.PlaceOrder.clickOnSubmitBtn();
        PageObjects.TitleExpectations.goToPurchaseSuccessfulPage();
        cy.get('[data-cy="homeDeliverySuccessfulNewSIM"]').should('have.text','Lookout for your new SIM Card in the mail!');
        cy.get('[data-cy="activateNewSIM"]').should('have.text',' Once your SIM card arrives in a couple of days, we will help you get your SIM card activated with a brand new phone number, or transfer your active number (port in) from another provider. You can view your plan details and activate it through your Purchased Plans page. ');
        cy.get('[data-cy="purchasedPlansBtn"]').click();
        PageObjects.TitleExpectations.goToPurchasedPlansPage();
    };
    purchase2GBPlanWithHomeDeliveryExistingCustomerHomePage(){
        cy.get('#home-header').click();
        PageObjects.TitleExpectations.goToHomePage();
        PageObjects.Plans.clickOnPlan_2_GB_Home_Page();
        PageObjects.TitleExpectations.goToPlansGMPage();
        PageObjects.Plans.clickOnPlan_2_GB_Plans_Page();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressIsRequired();
        PageObjects.Coverage.addressRefNotSelectedFromList();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressNotSelectedFromList();
        cy.get('[data-cy="addressRef"]').clear();
        PageObjects.Coverage.enterAddressRefBothCoverages();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        cy.get('.banner-content > .title').should('have.text', ' Great News!');
        PageObjects.Coverage.clickOnNextStepBtn();
        PageObjects.Compatibility.clickOnCheckYourDevice();
        PageObjects.Compatibility.assertIMEInumberRequired();
        PageObjects.Compatibility.enterIMEInumber(CONSTANT.COMPATIBILITY.NEWMEID.INVALID_MEID);
        PageObjects.Compatibility.assertIMEInumberInvalid();
        PageObjects.Compatibility.clickOnSkipForNowLink();
        PageObjects.Compatibility.clickOnYesFromThePopUp();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('.head-title').should('have.text', 'Review your cart');
        cy.get('[data-cy="basePlan"]').should('have.text','2GB 4G LTE Plan');
        cy.get('[data-cy="subtotal"]').should('have.text','Item(s) price: $10.00');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToShippingPage();
        PageObjects.ShippingPage.clickOnHomeDelivery();
        PageObjects.ShippingPage.selectShippingInfo();
        cy.get('select').eq(0).select('USPS', { force: true }).should('have.value', 'usps');
        cy.get('select').eq(1).select('First Class Mail Shipping 3-7 Business days', { force: true }).should('have.value', 'usps_first_class_mail/letter');
        PageObjects.ShippingPage.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.Payment.paymentRequired();
        PageObjects.Payment.selectFirstPaymentMethod();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('.subtotal').should('have.text', ' Total: $13.02 '); 
        cy.get('[data-cy="basePlan"]').should('have.text', '2GB 4G LTE Plan');
        cy.get('[data-cy="deliveryMethod"]').should('have.text', 'Home Delivery');
        PageObjects.PlaceOrder.clickOnSubmitBtn();
        PageObjects.TitleExpectations.goToPurchaseSuccessfulPage();
        cy.get('[data-cy="homeDeliverySuccessfulNewSIM"]').should('have.text','Lookout for your new SIM Card in the mail!');
        cy.get('[data-cy="activateNewSIM"]').should('have.text',' Once your SIM card arrives in a couple of days, we will help you get your SIM card activated with a brand new phone number, or transfer your active number (port in) from another provider. You can view your plan details and activate it through your Purchased Plans page. ');
        cy.get('[data-cy="purchasedPlansBtn"]').click();
        PageObjects.TitleExpectations.goToPurchasedPlansPage();
    };
    purchase6GBPlanWithHomeDeliveryExistingCustomerHomePage(){
        cy.get('#home-header').click();
        PageObjects.TitleExpectations.goToHomePage();
        PageObjects.Plans.clickOn6GB_From_Home_Page();
        PageObjects.TitleExpectations.goToPlansGMPage();
        PageObjects.Plans.clickOn6GB_From_Plans_Page();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressIsRequired();
        PageObjects.Coverage.addressRefNotSelectedFromList();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.Coverage.assertAddressNotSelectedFromList();
        cy.get('[data-cy="addressRef"]').clear();
        PageObjects.Coverage.enterAddressRefBothCoverages();
        PageObjects.Coverage.clickOnCheckCoverageBtn();
        PageObjects.TitleExpectations.goToCheckYourPhoneCompatibilityPage();
        cy.get('.banner-content > .title').should('have.text', ' Great News!');
        PageObjects.Coverage.clickOnNextStepBtn();
        PageObjects.Compatibility.clickOnCheckYourDevice();
        PageObjects.Compatibility.assertIMEInumberRequired();
        PageObjects.Compatibility.enterIMEInumber(CONSTANT.COMPATIBILITY.NEWMEID.INVALID_MEID);
        PageObjects.Compatibility.assertIMEInumberInvalid();
        PageObjects.Compatibility.clickOnSkipForNowLink();
        PageObjects.Compatibility.clickOnYesFromThePopUp();
        PageObjects.TitleExpectations.goToReviewCartPage();
        cy.get('.head-title').should('have.text', 'Review your cart');
        cy.get('[data-cy="basePlan"]').should('have.text','6GB 4G LTE Plan');
        cy.get('[data-cy="subtotal"]').should('have.text','Item(s) price: $20.00');
        PageObjects.ReviewCart.clickOnCheckoutBtn();
        PageObjects.TitleExpectations.goToShippingPage();
        PageObjects.ShippingPage.clickOnHomeDelivery();
        PageObjects.ShippingPage.selectShippingInfo();
        cy.get('select').eq(0).select('USPS', { force: true }).should('have.value', 'usps');
        cy.get('select').eq(1).select('First Class Mail Shipping 3-7 Business days', { force: true }).should('have.value', 'usps_first_class_mail/letter');
        PageObjects.ShippingPage.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPaymentPage();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.Payment.paymentRequired();
        PageObjects.Payment.selectFirstPaymentMethod();
        PageObjects.Payment.clickOnNextBtn();
        PageObjects.TitleExpectations.goToPlaceYourOrderPage();
        cy.get('.subtotal').should('have.text', ' Total: $24.54 ');
        cy.get('[data-cy="basePlan"]').should('have.text', '6GB 4G LTE Plan');
        cy.get('[data-cy="deliveryMethod"]').should('have.text', 'Home Delivery');
        PageObjects.PlaceOrder.clickOnSubmitBtn();
        PageObjects.TitleExpectations.goToPurchaseSuccessfulPage();
        cy.get('[data-cy="homeDeliverySuccessfulNewSIM"]').should('have.text','Lookout for your new SIM Card in the mail!');
        cy.get('[data-cy="activateNewSIM"]').should('have.text',' Once your SIM card arrives in a couple of days, we will help you get your SIM card activated with a brand new phone number, or transfer your active number (port in) from another provider. You can view your plan details and activate it through your Purchased Plans page. ');
        cy.get('[data-cy="purchasedPlansBtn"]').click();
        PageObjects.TitleExpectations.goToPurchasedPlansPage();
    };
};
export default new PurchasedPlans();
